services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: finance-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka-bootstrap:
    image: confluentinc/cp-kafka:7.6.0
    container_name: finance-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: finance-zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: finance-kafka-ui
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: finance-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: finance-kafka:9092
    depends_on:
      - kafka-bootstrap
